services:
  postgres:
    image: postgres:16-alpine
    container_name: workspace_db
    environment:
      POSTGRES_DB: WorkSpaceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: