GET http://localhost:5166/api/resources
Accept: application/json

###

GET http://localhost:5166/api/resources/1
Accept: application/json

###

POST http://localhost:5166/api/resources
Content-Type: application/json

{
  "name": "Meeting room Delta",
  "capacity": 52,
  "isAvailable": true
}

###

PUT http://localhost:5166/api/resources/4
Content-Type: application/json

{
  "id": 4,
  "name": "Meeting room Delta updated",
  "capacity": 43,
  "isAvailable": true
}

###

DELETE http://localhost:5166/api/resources/3